import { logger } from "../../utils/logger.js";
import { ApiError } from "../../utils/ApiError.js";
import { prisma } from "../../database/client.js";

export interface FingerprintVerificationResult {
  isValid: boolean;
  confidence: number;
  riskLevel: "low" | "medium" | "high";
  details: {
    visitorId: string;
    existingAccountsCount: number;
    message?: string;
  };
}

/**
 * Free Open-Source FingerprintJS Service
 * Based on https://github.com/fingerprintjs/fingerprintjs (MIT License)
 *
 * Runs 100% locally and free without external paid API keys (FINGERPRINT_API_KEY).
 * Evaluates browser device visitor IDs and enforces device-level abuse prevention
 * against multi-account trial farming.
 */
export class FingerprintService {
  /**
   * Validates the structure of an open-source FingerprintJS visitor ID.
   * Open-source FingerprintJS produces a 32-character hexadecimal browser hash
   * (or alphanumeric hash between 16 and 64 characters).
   */
  public isValidVisitorIdFormat(visitorId: string): boolean {
    if (!visitorId || typeof visitorId !== "string") return false;
    const trimmed = visitorId.trim();
    // 16 to 64 alphanumeric / hex characters
    return /^[a-zA-Z0-9_-]{16,64}$/.test(trimmed);
  }

  /**
   * verifyFingerprint
   * Validates the client-side visitor identifier and assesses account abuse risk.
   *
   * @param visitorId - 32-character browser fingerprint generated by @fingerprintjs/fingerprintjs
   * @param requestId - Optional backwards-compatibility parameter (not needed for open-source version)
   */
  async verifyFingerprint(
    visitorId: string,
    _requestId?: string,
  ): Promise<FingerprintVerificationResult> {
    try {
      if (!visitorId || !this.isValidVisitorIdFormat(visitorId)) {
        logger.warn("[FingerprintService] Invalid visitor ID format received", {
          visitorId,
        });
        throw new ApiError(400, "Invalid device fingerprint format");
      }

      // Check how many candidate profiles share this device fingerprint
      const existingAccountsCount = await prisma.candidateProfile.count({
        where: {
          deviceFingerprint: visitorId,
        },
      });

      let riskLevel: "low" | "medium" | "high" = "low";
      let confidence = 0.98;

      if (existingAccountsCount === 0) {
        riskLevel = "low";
        confidence = 0.99;
      } else {
        // Any existing account on the exact same browser/device blocks new account
        riskLevel = "high";
        confidence = 0.0;
      }

      const isAllowed = existingAccountsCount === 0;

      logger.info("[FingerprintService] Open-source fingerprint evaluated", {
        visitorId,
        existingAccountsCount,
        riskLevel,
        confidence,
        isAllowed,
      });

      return {
        isValid: isAllowed,
        confidence,
        riskLevel,
        details: {
          visitorId,
          existingAccountsCount,
          message:
            !isAllowed
              ? "This device is already associated with an existing Sensei account. Multiple accounts or account switching is blocked."
              : undefined,
        },
      };
    } catch (error) {
      if (error instanceof ApiError) throw error;
      logger.error("[FingerprintService] Verification error", error);
      throw new ApiError(500, "Failed to verify device fingerprint");
    }
  }

  /**
   * checkForDuplicates
   * Utility method to check if a visitor ID is associated with multiple
   * candidate accounts in the database.
   */
  async checkForDuplicates(
    visitorId: string,
    excludeCandidateId?: string,
  ): Promise<{ count: number; riskLevel: "low" | "medium" | "high" }> {
    if (!this.isValidVisitorIdFormat(visitorId)) {
      return { count: 0, riskLevel: "low" };
    }

    const count = await prisma.candidateProfile.count({
      where: {
        deviceFingerprint: visitorId,
        ...(excludeCandidateId ? { id: { not: excludeCandidateId } } : {}),
      },
    });

    const riskLevel: "low" | "medium" | "high" = count >= 1 ? "high" : "low";

    logger.info("[FingerprintService] Duplicate check completed", {
      visitorId,
      count,
      riskLevel,
    });

    return {
      count,
      riskLevel,
    };
  }
}

export const fingerprintService = new FingerprintService();
